/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FingerprintProtocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "FingerprintProtocol.pb-c.h"
void   textsecure__fingerprint_data__init
                     (Textsecure__FingerprintData         *message)
{
  static Textsecure__FingerprintData init_value = TEXTSECURE__FINGERPRINT_DATA__INIT;
  *message = init_value;
}
size_t textsecure__fingerprint_data__get_packed_size
                     (const Textsecure__FingerprintData *message)
{
  assert(message->base.descriptor == &textsecure__fingerprint_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t textsecure__fingerprint_data__pack
                     (const Textsecure__FingerprintData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &textsecure__fingerprint_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t textsecure__fingerprint_data__pack_to_buffer
                     (const Textsecure__FingerprintData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &textsecure__fingerprint_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Textsecure__FingerprintData *
       textsecure__fingerprint_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Textsecure__FingerprintData *)
     protobuf_c_message_unpack (&textsecure__fingerprint_data__descriptor,
                                allocator, len, data);
}
void   textsecure__fingerprint_data__free_unpacked
                     (Textsecure__FingerprintData *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &textsecure__fingerprint_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   textsecure__combined_fingerprint__init
                     (Textsecure__CombinedFingerprint         *message)
{
  static Textsecure__CombinedFingerprint init_value = TEXTSECURE__COMBINED_FINGERPRINT__INIT;
  *message = init_value;
}
size_t textsecure__combined_fingerprint__get_packed_size
                     (const Textsecure__CombinedFingerprint *message)
{
  assert(message->base.descriptor == &textsecure__combined_fingerprint__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t textsecure__combined_fingerprint__pack
                     (const Textsecure__CombinedFingerprint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &textsecure__combined_fingerprint__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t textsecure__combined_fingerprint__pack_to_buffer
                     (const Textsecure__CombinedFingerprint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &textsecure__combined_fingerprint__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Textsecure__CombinedFingerprint *
       textsecure__combined_fingerprint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Textsecure__CombinedFingerprint *)
     protobuf_c_message_unpack (&textsecure__combined_fingerprint__descriptor,
                                allocator, len, data);
}
void   textsecure__combined_fingerprint__free_unpacked
                     (Textsecure__CombinedFingerprint *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &textsecure__combined_fingerprint__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor textsecure__fingerprint_data__field_descriptors[2] =
{
  {
    "publicKey",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Textsecure__FingerprintData, has_publickey),
    offsetof(Textsecure__FingerprintData, publickey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identifier",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Textsecure__FingerprintData, has_identifier),
    offsetof(Textsecure__FingerprintData, identifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned textsecure__fingerprint_data__field_indices_by_name[] = {
  1,   /* field[1] = identifier */
  0,   /* field[0] = publicKey */
};
static const ProtobufCIntRange textsecure__fingerprint_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor textsecure__fingerprint_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "textsecure.FingerprintData",
  "FingerprintData",
  "Textsecure__FingerprintData",
  "textsecure",
  sizeof(Textsecure__FingerprintData),
  2,
  textsecure__fingerprint_data__field_descriptors,
  textsecure__fingerprint_data__field_indices_by_name,
  1,  textsecure__fingerprint_data__number_ranges,
  (ProtobufCMessageInit) textsecure__fingerprint_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor textsecure__combined_fingerprint__field_descriptors[3] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Textsecure__CombinedFingerprint, has_version),
    offsetof(Textsecure__CombinedFingerprint, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "localFingerprint",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Textsecure__CombinedFingerprint, localfingerprint),
    &textsecure__fingerprint_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remoteFingerprint",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Textsecure__CombinedFingerprint, remotefingerprint),
    &textsecure__fingerprint_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned textsecure__combined_fingerprint__field_indices_by_name[] = {
  1,   /* field[1] = localFingerprint */
  2,   /* field[2] = remoteFingerprint */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange textsecure__combined_fingerprint__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor textsecure__combined_fingerprint__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "textsecure.CombinedFingerprint",
  "CombinedFingerprint",
  "Textsecure__CombinedFingerprint",
  "textsecure",
  sizeof(Textsecure__CombinedFingerprint),
  3,
  textsecure__combined_fingerprint__field_descriptors,
  textsecure__combined_fingerprint__field_indices_by_name,
  1,  textsecure__combined_fingerprint__number_ranges,
  (ProtobufCMessageInit) textsecure__combined_fingerprint__init,
  NULL,NULL,NULL    /* reserved[123] */
};
