/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: FingerprintProtocol.proto */

#ifndef PROTOBUF_C_FingerprintProtocol_2eproto__INCLUDED
#define PROTOBUF_C_FingerprintProtocol_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Textsecure__FingerprintData Textsecure__FingerprintData;
typedef struct _Textsecure__CombinedFingerprint Textsecure__CombinedFingerprint;


/* --- enums --- */


/* --- messages --- */

struct  _Textsecure__FingerprintData
{
  ProtobufCMessage base;
  protobuf_c_boolean has_publickey;
  ProtobufCBinaryData publickey;
  protobuf_c_boolean has_identifier;
  ProtobufCBinaryData identifier;
};
#define TEXTSECURE__FINGERPRINT_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&textsecure__fingerprint_data__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL} }


struct  _Textsecure__CombinedFingerprint
{
  ProtobufCMessage base;
  protobuf_c_boolean has_version;
  uint32_t version;
  Textsecure__FingerprintData *localfingerprint;
  Textsecure__FingerprintData *remotefingerprint;
};
#define TEXTSECURE__COMBINED_FINGERPRINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&textsecure__combined_fingerprint__descriptor) \
    , 0,0, NULL, NULL }


/* Textsecure__FingerprintData methods */
void   textsecure__fingerprint_data__init
                     (Textsecure__FingerprintData         *message);
size_t textsecure__fingerprint_data__get_packed_size
                     (const Textsecure__FingerprintData   *message);
size_t textsecure__fingerprint_data__pack
                     (const Textsecure__FingerprintData   *message,
                      uint8_t             *out);
size_t textsecure__fingerprint_data__pack_to_buffer
                     (const Textsecure__FingerprintData   *message,
                      ProtobufCBuffer     *buffer);
Textsecure__FingerprintData *
       textsecure__fingerprint_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   textsecure__fingerprint_data__free_unpacked
                     (Textsecure__FingerprintData *message,
                      ProtobufCAllocator *allocator);
/* Textsecure__CombinedFingerprint methods */
void   textsecure__combined_fingerprint__init
                     (Textsecure__CombinedFingerprint         *message);
size_t textsecure__combined_fingerprint__get_packed_size
                     (const Textsecure__CombinedFingerprint   *message);
size_t textsecure__combined_fingerprint__pack
                     (const Textsecure__CombinedFingerprint   *message,
                      uint8_t             *out);
size_t textsecure__combined_fingerprint__pack_to_buffer
                     (const Textsecure__CombinedFingerprint   *message,
                      ProtobufCBuffer     *buffer);
Textsecure__CombinedFingerprint *
       textsecure__combined_fingerprint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   textsecure__combined_fingerprint__free_unpacked
                     (Textsecure__CombinedFingerprint *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Textsecure__FingerprintData_Closure)
                 (const Textsecure__FingerprintData *message,
                  void *closure_data);
typedef void (*Textsecure__CombinedFingerprint_Closure)
                 (const Textsecure__CombinedFingerprint *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor textsecure__fingerprint_data__descriptor;
extern const ProtobufCMessageDescriptor textsecure__combined_fingerprint__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_FingerprintProtocol_2eproto__INCLUDED */
